### ISSUE TITLE
教育部客話輸入法造字

### ISSUE THREAD

**Issue by sih4sing5hong5** [glll4678/tauhu-oo#1]
![未命名](https://user-images.githubusercontent.com/5996555/56125780-477e8b80-5fac-11e9-9656-0f580dd19056.png)

##  Unicode有ê
        - 𫣆	⿰亻恩	U+2B8C6
        - 𫠛	⿰齒星	U+2B81B
        - 𫝘	⿰口尢	U+2B758
        - 𬠖	⿰虫念	U+2C816  (e725)
        - 𫟧	⿺辶丁	U+2B7E7
        - 𫞭	⿸疒財	U+2B7AD
## 無unicode ê
        - ⿺皮卜 E76F
        - ⿰韋亥 E79C

**Comment by glll4678** [comment]
我知輸入法有這，毋過輸入法的詞庫看起來真亂，應該是舊的資料、無咧維護更新。
而且佇咧其他的資料無看著相關用字，就暫時無欲收。

**Comment by sih4sing5hong5** [comment]
舊年教育部客話輸入法ê規範，毋過感覺in客話攏bô tih顧這，莫做嘛好
