### ISSUE TITLE
thai-ko ê `ko` in Ext-G

### ISSUE THREAD

**Issue by sih4sing5hong5** [glll4678/tauhu-oo#2]
Ti [外字表](https://docs.google.com/spreadsheets/d/1RPN_4sVAYlHaMchak1wwf2dpNKRcLil7WFHkB1ZGVuE/edit#gid=1018353923)有註明`ko`會編入`ext-G`，這資料應該按ná揣？

![2019-09-30 16-06-27 的螢幕擷圖](https://user-images.githubusercontent.com/5996555/65860167-4e535c00-e39c-11e9-9de7-9a284579c2ac.png)

**Comment by justinrleung** [comment]
⿸疒哥 = `U+308FB` = 𰣻
⿰車藏 = `U+30E6C` = 𰹬

**Comment by glll4678** [comment]
佇咧 [IRG 官方網站](https://appsrv.cse.cuhk.edu.hk/~irg/index.htm) 看著的。
Ext-G 當初是 IRG WS 2015。
這馬有一个 IRG WS 2017，以後應該就會是 Ext-H？
（內面有一字「⿰皮卜」，佮客語「⿺皮卜」類似，毋過無仝。）

**Comment by sih4sing5hong5** [comment]
原來是看這，感恩～
