### ISSUE TITLE
README ē-sái koh 補充 Noto CJK

### ISSUE THREAD

**Issue by a8568730** [glll4678/tauhu-oo#4]
# Tsit-má ê README
若需要其他語言文字，會使佮 [Google Noto Fonts](https://www.google.com/get/noto/) 做伙使用。
# Ǹg-bāng
若需要其他語言文字，會使佮 [Google Noto Fonts](https://www.google.com/get/noto/) 做伙使用，尤其繁體中文會使參 [Google Noto CJK TC Regular](https://fonts.google.com/specimen/Noto+Sans+TC?selection.family=Noto+Sans+TC)。

**Comment by glll4678** [comment]
豆腐烏已經共 Big5 的字攏包入去矣，所以免閣用 Noto Sans CJK。
